### ISSUE TITLE
Progress: API

### ISSUE THREAD

**Issue by prezzemolo** [prezzemolo/pomodori#8]
## Time #1 
- [x] **time/epoch** ... return server epoch time
- [x] **time/iso8601** ... return server iso8601 time
## global IP #6 
- [x] **ip/remote** ... return remote address
## Meta #9 
- [x] **meta** ... return meta data
## base64 #12
- [x] **base64/encode** ... return base64 encorded string
- [x] **base64/decode** ... return base64 decodrded string
## nicovideo wrap #13, #23 
- [x] **nicovideo/info** ... return informations
- [ ] **nicovideo/export** ... return database file
## UUID #16 
- [x] **uuid/generate** ... return UUID
